# Generated by Django 4.0.1 on 2023-03-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cart_prod', models.CharField(max_length=10)),
                ('cart_qty', models.IntegerField(max_length=8)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=20)),
                ('mem_regno1', models.CharField(max_length=6)),
                ('mem_regno2', models.CharField(max_length=7)),
                ('mem_bir', models.DateTimeField()),
                ('mem_zip', models.CharField(max_length=7)),
                ('mem_add1', models.CharField(max_length=100)),
                ('mem_add2', models.CharField(max_length=80)),
                ('mem_hometel', models.CharField(max_length=14)),
                ('mem_comtel', models.CharField(max_length=14)),
                ('mem_hp', models.CharField(max_length=15)),
                ('mem_mail', models.CharField(max_length=40)),
                ('mem_job', models.CharField(max_length=40)),
                ('mem_like', models.CharField(max_length=40)),
                ('mem_memorial', models.CharField(max_length=40)),
                ('mem_memorialday', models.DateTimeField()),
                ('mem_mileage', models.IntegerField(max_length=10)),
                ('mem_delete', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
