# Generated by Django 4.0.1 on 2023-03-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
